#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		echo
		echo "FAILED"
		echo
		exit 1
	fi
}

cd make; make; check_okay; cd ..

for m in 1 3 10 30
do
    mkdir -p ${m}M/LOGS
    mkdir -p ${m}M/photos
    mkdir -p ${m}M/frames
    mkdir -p ${m}M/experiments
done
