#!/bin/bash

function do_one {
    INLIST="inlist_${1}_header"
    if [ ! -e "${INLIST}" ]
    then
        echo "target inlist file ${INLIST} does not exist"
        exit 1
    fi
    cp "${INLIST}" inlist
    echo 'run' "$1"
    if ! ./rn1
    then
        echo "rn1 failed"
        exit 1
    fi
    echo
    echo "finished $1"
    echo
}

for m in 1 3 10 30
do
    do_one ${m}M
done

echo 'finished'
