#!/usr/bin/env bash

caches=(eosDT eosPT ionization kap rates weaklib)

if [[ `uname -n` == 'starmaker.pa.msu.edu' ]]; then
	echo "on starmaker: "
	echo "cache output will be directed to $HOME/mesa_caches"
    echo
    
    if [[ ! -d $HOME/mesa_caches ]]; then
	    echo "making MESA cache directories in $HOME/mesa_caches"
	    mkdir $HOME/mesa_caches
	    for c in ${caches[@]}; do
		    mkdir $HOME/mesa_caches/${c}_cache
	    done
    else
        echo "cache directories exist"
    fi
    echo

    echo "writing set_caches.inlist"
    cp set_caches.inlist tmp.inlist
    nom=`whoami`
    sed "{
        s/whoami/$nom/g
        s/^!//g
    }" tmp.inlist > set_caches.inlist
    rm tmp.inlist
    echo "done"
fi
